# Generated by Django 4.1.7 on 2023-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0002_remove_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='base.conversation'),
        ),
    ]
