# Generated by Django 4.1.7 on 2023-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_conversation_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(to='base.message'),
        ),
    ]
